/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/8.1.1/userguide/multi_project_builds.html
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    // Include 'plugins build' to define convention plugins.
    includeBuild("build-logic")
}

plugins {
    kotlin("jvm") version "1.8.10" apply false
//    id("com.autonomousapps.dependency-analysis") version "1.19.0"
    id("io.ktor.plugin") version "2.3.0" apply false // TODO: Just the ktor module needs this.
//    id("org.jetbrains.kotlin.plugin.serialization") version "1.8.10" apply false
    kotlin("plugin.serialization") version "1.8.21" apply false
    id("org.jmailen.kotlinter") version "3.14.0" apply false

}

rootProject.name = "kafkagram"
include("telegram-webhook", "telegram-response", "telegram-echo", "telegram-model")

