on:
  push:
    branches:
      - master
jobs:
  build-with-paketo-push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install pack CLI via the official buildpack Action https://github.com/buildpacks/github-actions#setup-pack-cli-action
        uses: buildpacks/github-actions/setup-pack@v4.9.1

      - name: Set BP_GRADLE_BUILT_ARTIFACT
        run: echo "BP_GRADLE_BUILT_ARTIFACT=telegram-webhook/build/libs/*.jar " >> $GITHUB_ENV

      - name: Build telegram-webhook with pack CLI using Buildpack
        env:
          BP_GRADLE_BUILT_ARTIFACT: telegram-webhook/build/libs/*.jar
        run: |
          pack build bthode/telegram-webhook:latest \
          --builder paketobuildpacks/builder:base \
          --path . \
          --env BP_GRADLE_BUILT_ARTIFACT=$BP_GRADLE_BUILT_ARTIFACT \
          --publish

      - name: Build telegram-echo with pack CLI using Buildpack
        env:
          BP_GRADLE_BUILT_ARTIFACT: telegram-echo/build/libs/*.jar
        run: |
          pack build bthode/telegram-echo:latest \
          --builder paketobuildpacks/builder:base \
          --path . \
          --env BP_GRADLE_BUILT_ARTIFACT=$BP_GRADLE_BUILT_ARTIFACT \
          -- cache-dir /home/cnb/.gradle \
          --publish

      - name: Build telegram-response with pack CLI using Buildpack
        env:
          BP_GRADLE_BUILT_ARTIFACT: telegram-response/build/libs/*.jar
        run: |
          pack build bthode/telegram-response:latest \
          --builder paketobuildpacks/builder:base \
          --path . \
          --env BP_GRADLE_BUILT_ARTIFACT=$BP_GRADLE_BUILT_ARTIFACT \
          -- cache-dir /home/cnb/.gradle \
          --publish
