on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up pack CLI
        uses: paketobuildpacks/builder
        with:
          version: "latest"

      - name: Build and publish Docker image with pack
        env:
          DOCKER_IMAGE_NAME: telegram-webhook
        run: |
          pack set-default-builder heroku/buildpacks:18
          pack build "${DOCKER_IMAGE_NAME}" --path telegram-webhook --publish docker.io/"${DOCKER_IMAGE_NAME}"
