on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up pack CLI
        uses: paketobuildpacks/builder
        with:
          version: "latest"

      - name: Build and publish Docker image with pack
        env:
          DOCKER_IMAGE_NAME: telegram-webhook
        run: |
          pack build bthode/telegram-webhook --builder cnb-builder \
          --registry https://index.docker.io/v1/ \
          --docker-username ${{ secrets.DOCKERHUB_USERNAME }} \
          --docker-password ${{ secrets.DOCKERHUB_TOKEN }}
